name: Aktualizace Meteostanice
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-meteo:
    runs-on: ubuntu-latest
    env:
      TUYA_API_KEY: ${{ secrets.TUYA_API_KEY }}
      TUYA_API_SECRET: ${{ secrets.TUYA_API_SECRET }}
      TUYA_DEVICE_ID: ${{ secrets.TUYA_DEVICE_ID }}
      ZIVY_OBRAZ_KEY: ${{ secrets.ZIVY_OBRAZ_KEY }}
    steps:
      - name: Načtení kódu
        uses: actions/checkout@v4
      - name: Nastavení Pythonu
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Instalace knihoven
        run: pip install requests tinytuya
      - name: Spuštění skriptu
        run: python meteo.py

#

#
