name: Aktualizace Meteostanice
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: # Umožní spustit skript i ručně tlačítkem

jobs:
  run-meteo:
    runs-on: ubuntu-latest
    steps:
      - name: Načtení kódu
        uses: actions/checkout@v4
      - name: Nastavení Pythonu
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Instalace knihoven
        run: pip install requests tinytuya
      - name: Spuštění skriptu
        run: python meteo.py
